### ISSUE TITLE
README のリファレンスへのリンクが誤っているようです

### ISSUE THREAD

**Issue by monmon** [payjp/payjp-android#72]
- 誤
    - https://payjp.github.io/payjp-android/payjp-android/
- 正
    - https://payjp.github.io/payjp-android/

https://github.com/payjp/payjp-android/blob/10b9a86d0b7e93a30718e9878508f7da9bb64e99/README.md

**Comment by yatatsu** [comment]
@monmon ありがとうございます、対応しました。
